import type { ServiceRequest, Worker } from "./types";

export const customerPosition = { lat: -32.8895, lng: -68.8458 };

export const initialWorkers: Worker[] = [
  {
    id: "w-1",
    name: "Martin Silva",
    trade: "Plomeria",
    rating: 4.9,
    jobs: 182,
    eta: 12,
    distance: 2.4,
    status: "Libre",
    initials: "MS",
    verified: true,
    license: "Matricula sanitaria Mendoza 18392",
    position: { lat: -32.9187, lng: -68.8446 },
  },
  {
    id: "w-2",
    name: "Lucia Gomez",
    trade: "Electricidad",
    rating: 4.8,
    jobs: 137,
    eta: 18,
    distance: 3.1,
    status: "Terminando",
    initials: "LG",
    verified: true,
    license: "Electricista matriculada APSE",
    position: { lat: -32.8881, lng: -68.7987 },
  },
  {
    id: "w-3",
    name: "Raul Medina",
    trade: "Gas",
    rating: 4.7,
    jobs: 95,
    eta: 24,
    distance: 4.6,
    status: "Libre",
    initials: "RM",
    verified: true,
    license: "Gasista matriculado categoria 2",
    position: { lat: -32.8529, lng: -68.8358 },
  },
  {
    id: "w-4",
    name: "Sofia Alvarez",
    trade: "Climatizacion",
    rating: 4.9,
    jobs: 211,
    eta: 29,
    distance: 5.2,
    status: "Libre",
    initials: "SA",
    verified: true,
    license: "Tecnica certificada HVAC",
    position: { lat: -32.9834, lng: -68.7891 },
  },
];

export const initialRequests: ServiceRequest[] = [
  {
    id: "REQ-1024",
    clientName: "Carolina Perez",
    trade: "Plomeria",
    address: "Av. San Martin 1120, Ciudad de Mendoza",
    urgency: "Ahora",
    status: "En camino",
    workerId: "w-1",
    createdAt: "2026-06-26 10:12",
  },
  {
    id: "REQ-1025",
    clientName: "Diego Ramos",
    trade: "Electricidad",
    address: "Belgrano 780, Godoy Cruz",
    urgency: "Hoy",
    status: "Pendiente",
    createdAt: "2026-06-26 10:28",
  },
  {
    id: "REQ-1026",
    clientName: "Mariana Castro",
    trade: "Gas",
    address: "Sarmiento 640, Guaymallen",
    urgency: "Esta semana",
    status: "Aceptado",
    workerId: "w-3",
    createdAt: "2026-06-26 09:47",
  },
];
